import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';

test('页面真实数据加载、筛选、备选、详情、导出和导航交互', async () => {
  const html=await readFile(new URL('../site/index.html',import.meta.url),'utf8');
  const dom=new JSDOM(html,{url:'https://example.test/guangxi-admissions-2026/'});
  const {window}=dom;
  globalThis.document=window.document;globalThis.window=window;globalThis.localStorage=window.localStorage;
  globalThis.fetch=async url=>({ok:true,status:200,json:async()=>JSON.parse(await readFile(url,'utf8'))});
  window.HTMLElement.prototype.scrollIntoView=function(){};
  if(!window.HTMLDialogElement.prototype.showModal)window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
  if(!window.HTMLDialogElement.prototype.close)window.HTMLDialogElement.prototype.close=function(){this.open=false;};
  let download;
  window.HTMLAnchorElement.prototype.click=function(){download={name:this.download,href:this.href};};
  await import('../site/app.js?interaction-test');
  for(let i=0;i<200&&document.documentElement.dataset.ready===undefined;i++)await new Promise(resolve=>setTimeout(resolve,10));
  assert.equal(document.documentElement.dataset.ready,'true');
  const $=id=>document.getElementById(id);
  const input=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new window.Event('input',{bubbles:true}));};
  assert.ok(document.querySelectorAll('.result-card').length>0);
  assert.match($('coverage-strip').textContent,/8,155/);
  input('query','广西大学');input('kind','all');input('batch','all');
  document.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/该校专业计划来源/);
  assert.match($('detail-content').textContent,/已采集部分计划/);
  assert.ok(document.querySelector('#detail-content .plan-source-panel a[href^="https:"]'));
  document.querySelector('#detail-content [data-school-query]').click();
  assert.equal($('detail').open,false);assert.equal($('query').value,'10593');
  assert.equal($('result-title').textContent,'专业招生计划');assert.equal($('track').value,'物理');
  assert.ok(document.querySelectorAll('.result-card').length>0);
  document.querySelector('[data-view="cutoffs"]').click();$('reset').click();
  input('query','10593');input('track','历史');input('kind','all');input('batch','本科普通批');input('round','第一次征集');
  const supplementaryCard=[...document.querySelectorAll('.result-card')].find(card=>card.querySelector('.group-tag')?.textContent.includes('111'));
  assert.ok(supplementaryCard);supplementaryCard.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/本轮征集剩余计划（1 条）/);
  assert.match($('detail-content').textContent,/本轮剩余 2 人/);
  assert.match($('detail-content').textContent,/不是初始计划人数/);$('close-detail').click();
  input('round','首轮');document.querySelector('[data-detail]').click();
  assert.ok(!$('detail-content').textContent.includes('本轮剩余'));
  $('close-detail').click();$('reset').click();
  input('query','10559');input('kind','all');input('batch','本科普通批');
  const newGroup=[...document.querySelectorAll('.result-card')].find(card=>card.querySelector('.group-tag')?.textContent==='103 组');
  assert.ok(newGroup);newGroup.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/专业计划（3 条）/);assert.match($('detail-content').textContent,/网络与新媒体/);
  $('close-detail').click();input('query','10533');document.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/已收录该校 26 条计划/);
  document.querySelector('#detail-content [data-school-query]').click();
  assert.ok([...document.querySelectorAll('.score')].every(e=>e.textContent==='待匹配'));
  document.querySelector('[data-detail]').click();assert.match($('detail-content').textContent,/高校原文组名（广西组码待核）/);
  $('close-detail').click();document.querySelector('[data-view="cutoffs"]').click();$('reset').click();
  input('query','10358');input('round','首轮');input('kind','all');
  document.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/本组还没有可严格匹配/);
  assert.match($('detail-content').textContent,/已收录该校 12 条计划/);
  document.querySelector('#detail-content [data-school-query]').click();
  assert.equal($('result-title').textContent,'专业招生计划');
  assert.equal(document.querySelectorAll('.result-card').length,12);
  assert.ok([...document.querySelectorAll('.score')].every(e=>e.textContent==='待匹配'));
  const variants=[...document.querySelectorAll('.result-card')].filter(e=>e.textContent.includes('理科试验班类（拔尖计划科技英才班）'));
  assert.equal(variants.length,2);
  const variantDetails=variants.map(card=>{card.querySelector('[data-detail]').click();const text=$('detail-content').textContent;$('close-detail').click();return text;});
  assert.ok(variantDetails.some(t=>t.includes('华罗庚')));assert.ok(variantDetails.some(t=>t.includes('卢嘉锡')));
  document.querySelector('[data-view="cutoffs"]').click();$('reset').click();
  input('value','550');
  input('unknown','');$('unknown').checked=false;$('unknown').dispatchEvent(new window.Event('input',{bubbles:true}));
  const scores=[...document.querySelectorAll('.score-box .score')].map(e=>Number(e.textContent));
  assert.ok(scores.length>0);assert.ok(scores.every(s=>s>=530&&s<=570));
  input('value','751');assert.match($('results-list').textContent,/请先修正输入/);
  input('value','550');input('query','不存在的学校XYZ');assert.equal(document.querySelectorAll('.result-card').length,0);
  input('query','');
  const save=document.querySelector('[data-save]');assert.ok(save);save.click();
  assert.equal($('saved-count').textContent,'1');assert.equal(JSON.parse(localStorage.getItem('guangxi-admissions-2026-shortlist-v1')).length,1);
  document.querySelector('[data-detail]').click();assert.equal($('detail').open,true);assert.match($('detail-content').textContent,/2026/);$('close-detail').click();assert.equal($('detail').open,false);
  $('export').click();assert.equal(download.name,'广西2026志愿备选.csv');assert.match(download.href,/^blob:/);
  $('mode').value='rank';$('mode').dispatchEvent(new window.Event('change',{bubbles:true}));input('value','20000');assert.match($('reference-note').textContent,/对应 2026 参考分/);
  input('track','历史');assert.match($('current-summary').textContent,/历史/);
  document.querySelector('[data-view="plans"]').click();assert.equal($('subjects-field').hidden,false);
  input('value','');input('track','物理');input('kind','all');input('query','桂林');assert.ok(document.querySelectorAll('.result-card').length>0);
  const checks=[...document.querySelectorAll('[name=subject]')];for(const check of checks.slice(0,3)){check.checked=true;check.dispatchEvent(new window.Event('input',{bubbles:true}));}assert.equal(document.querySelectorAll('[name=subject]:checked').length,2);
  document.querySelector('[data-view="majorCutoffs"]').click();assert.equal($('result-title').textContent,'专业实际录取分数');
  assert.equal($('round').value,'all','专业线入口不能默认隐藏高校汇总数据');
  input('query','玉林');input('batch','all');input('round','首轮');assert.ok(document.querySelectorAll('.result-card').length>0);assert.equal($('round-field').hidden,false);
  input('query','齐齐哈尔');input('round','录取汇总（含征集）');assert.ok(document.querySelectorAll('.result-card').length>0);assert.match($('results-list').textContent,/录取汇总（含征集）/);
  document.querySelector('[data-view="cutoffs"]').click();$('reset').click();
  input('query','10601');input('track','物理');input('kind','all');input('batch','all');
  document.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/该校专业录取分数/);
  assert.match($('detail-content').textContent,/不代表本组已全部匹配/);
  document.querySelector('#detail-content [data-destination="majorCutoffs"]').click();
  assert.equal($('detail').open,false);assert.equal($('query').value,'10601');assert.equal($('track').value,'物理');assert.equal($('round').value,'all');
  assert.match($('result-count').textContent,/51 条/);
  input('kind','general');assert.ok(![...document.querySelectorAll('.result-card')].some(r=>/定向医学生|民族班/.test(r.textContent)));
  input('query','中澳');assert.match($('results-list').textContent,/中澳学分互认联合培养项目/);
  assert.match($('results-list').textContent,/90/);assert.match($('results-list').textContent,/60%/);
  input('kind','all');input('query','11765');
  const conflict=[...document.querySelectorAll('.result-card')].find(r=>r.textContent.includes('城市地下空间工程'));
  assert.ok(conflict);assert.equal(conflict.querySelector('.score').textContent,'原文待核');conflict.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/428.2/);assert.match($('detail-content').textContent,/423/);$('close-detail').click();
  $('unknown').checked=false;$('unknown').dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.ok(![...document.querySelectorAll('.result-card')].some(r=>r.textContent.includes('城市地下空间工程')));
  $('unknown').checked=true;$('unknown').dispatchEvent(new window.Event('input',{bubbles:true}));
  input('query','10637');input('round','征集（次数未分）');assert.match($('results-list').textContent,/食品质量与安全/);
  assert.equal(document.querySelectorAll('.result-card').length,1);
  input('query','10052');input('track','历史');input('round','all');input('kind','general');
  assert.ok(document.querySelectorAll('.result-card').length>0);
  assert.ok(![...document.querySelectorAll('.result-card')].some(r=>/民族班|国家专项/.test(r.textContent)));
  document.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/专业最低分排名（学校公布）/);
  assert.match($('detail-content').textContent,/高校公布位次/);
  assert.match($('detail-content').textContent,/采集：2026-09-11/);$('close-detail').click();
  input('query','16302');input('kind','all');
  assert.equal(document.querySelectorAll('.result-card').length,1);
  assert.equal(document.querySelector('.group-tag').textContent,'组码待核');
  document.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/正式招生大类最低分/);
  assert.match($('detail-content').textContent,/招生与培养要求/);
  assert.match($('detail-content').textContent,/完成大一第一学期后选专业/);
  assert.match($('detail-content').textContent,/历史\+不限/);$('close-detail').click();
  input('query','11319');input('track','物理');input('kind','all');
  assert.ok([...document.querySelectorAll('.result-card')].some(r=>/定向/.test(r.textContent)));
  input('kind','general');
  assert.ok(![...document.querySelectorAll('.result-card')].some(r=>/定向/.test(r.textContent)));
  document.querySelector('[data-detail]').click();
  assert.match($('detail-content').textContent,/来源记载最低分位次（待核）/);$('close-detail').click();
  document.querySelector('[data-view="special"]').click();assert.equal($('special-view').hidden,false);assert.equal($('query-layout').hidden,true);
  input('special-query','哈尔滨工业大学');assert.match($('special-list').textContent,/100 分制/);assert.match($('special-list').textContent,/加权成绩入围线/);assert.ok(!$('special-list').textContent.includes('entrance-weighted'));
  input('special-query','厦门大学');assert.match($('special-list').textContent,/1000 分制/);
  input('special-query','华中科技大学');assert.ok([...document.querySelectorAll('#special-list .detail-plan strong')].some(e=>e.textContent==='化学：519 分'));assert.match($('special-list').textContent,/519\.097109105/);
  input('special-query','中央民族大学');assert.match($('special-list').textContent,/广西计划：本省不适用/);
  input('special-query','重庆大学');assert.match($('special-list').textContent,/本轮原页无法重读/);
  input('special-query','不存在的大学XYZ');assert.match($('special-list').textContent,/没有匹配/);
  document.querySelector('[data-view="sources"]').click();assert.equal($('sources-view').hidden,false);assert.match($('coverage-detail').textContent,/部分覆盖/);
  assert.match($('coverage-detail').textContent,/最近补采或核查：2026-09-11（北京时间）/);
  assert.ok(document.querySelectorAll('#sources-list a').length>=18);
  document.querySelector('[data-view="gaps"]').click();assert.equal($('gaps-view').hidden,false);assert.equal($('query-layout').hidden,true);
  assert.match($('gap-overview').textContent,/1,961/);
  input('gap-query','广西大学');assert.match($('gap-list').textContent,/专业组代码/);assert.equal(document.querySelectorAll('.gap-card').length,1);
  document.querySelector('[data-school-query][data-destination="plans"]').click();assert.equal($('query').value,'10593');assert.equal($('query-layout').hidden,false);assert.equal($('kind').value,'all');
  assert.ok(document.querySelectorAll('.result-card').length>0);document.querySelector('[data-detail]').click();assert.match($('detail-content').textContent,/本专业尚待核实或关联/);$('close-detail').click();
  document.querySelector('[data-view="gaps"]').click();input('gap-query','不存在的院校XYZ');assert.match($('gap-list').textContent,/没有匹配院校/);
  input('gap-query','重庆三峡医药');document.querySelector('[data-school-query][data-destination="majorCutoffs"]').click();
  assert.ok([...document.querySelectorAll('.score.empty')].some(e=>e.textContent==='原文待核'));
  $('unknown').checked=false;$('unknown').dispatchEvent(new window.Event('input',{bubbles:true}));assert.equal(document.querySelectorAll('.score.empty').length,0);
  assert.equal(document.querySelectorAll('a[href^="javascript:"]').length,0);
  dom.window.close();
});

test('文件加载失败显示可恢复提示，不把空数据当作成功', async()=>{
  const html=await readFile(new URL('../site/index.html',import.meta.url),'utf8');
  const dom=new JSDOM(html,{url:'https://example.test/'});
  globalThis.document=dom.window.document;globalThis.window=dom.window;globalThis.localStorage=dom.window.localStorage;
  globalThis.fetch=async()=>({ok:false,status:503});
  await import('../site/app.js?error-test');
  for(let i=0;i<100&&document.documentElement.dataset.ready===undefined;i++)await new Promise(resolve=>setTimeout(resolve,10));
  assert.equal(document.documentElement.dataset.ready,'error');
  assert.equal(document.getElementById('data-error').hidden,false);
  assert.match(document.getElementById('error-detail').textContent,/503/);
  dom.window.close();
});
