import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';

test('页面真实数据加载、筛选、备选、详情、导出和导航交互', async () => {
  const html=await readFile(new URL('../site/index.html',import.meta.url),'utf8');
  const dom=new JSDOM(html,{url:'https://example.test/guangxi-admissions-2026/'});
  const {window}=dom;
  globalThis.document=window.document;globalThis.window=window;globalThis.localStorage=window.localStorage;
  globalThis.fetch=async url=>({ok:true,status:200,json:async()=>JSON.parse(await readFile(url,'utf8'))});
  window.HTMLElement.prototype.scrollIntoView=function(){};
  if(!window.HTMLDialogElement.prototype.showModal)window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
  if(!window.HTMLDialogElement.prototype.close)window.HTMLDialogElement.prototype.close=function(){this.open=false;};
  let download;
  window.HTMLAnchorElement.prototype.click=function(){download={name:this.download,href:this.href};};
  await import('../site/app.js?interaction-test');
  for(let i=0;i<200&&document.documentElement.dataset.ready===undefined;i++)await new Promise(resolve=>setTimeout(resolve,10));
  assert.equal(document.documentElement.dataset.ready,'true');
  const $=id=>document.getElementById(id);
  const input=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new window.Event('input',{bubbles:true}));};
  assert.ok(document.querySelectorAll('.result-card').length>0);
  assert.match($('coverage-strip').textContent,/8,155/);
  input('value','550');
  input('unknown','');$('unknown').checked=false;$('unknown').dispatchEvent(new window.Event('input',{bubbles:true}));
  const scores=[...document.querySelectorAll('.score-box .score')].map(e=>Number(e.textContent));
  assert.ok(scores.length>0);assert.ok(scores.every(s=>s>=530&&s<=570));
  input('value','751');assert.match($('results-list').textContent,/请先修正输入/);
  input('value','550');input('query','不存在的学校XYZ');assert.equal(document.querySelectorAll('.result-card').length,0);
  input('query','');
  const save=document.querySelector('[data-save]');assert.ok(save);save.click();
  assert.equal($('saved-count').textContent,'1');assert.equal(JSON.parse(localStorage.getItem('guangxi-admissions-2026-shortlist-v1')).length,1);
  document.querySelector('[data-detail]').click();assert.equal($('detail').open,true);assert.match($('detail-content').textContent,/2026/);$('close-detail').click();assert.equal($('detail').open,false);
  $('export').click();assert.equal(download.name,'广西2026志愿备选.csv');assert.match(download.href,/^blob:/);
  $('mode').value='rank';$('mode').dispatchEvent(new window.Event('change',{bubbles:true}));input('value','20000');assert.match($('reference-note').textContent,/对应 2026 参考分/);
  input('track','历史');assert.match($('current-summary').textContent,/历史/);
  document.querySelector('[data-view="plans"]').click();assert.equal($('subjects-field').hidden,false);
  input('value','');input('track','物理');input('kind','all');input('query','桂林');assert.ok(document.querySelectorAll('.result-card').length>0);
  const checks=[...document.querySelectorAll('[name=subject]')];for(const check of checks.slice(0,3)){check.checked=true;check.dispatchEvent(new window.Event('input',{bubbles:true}));}assert.equal(document.querySelectorAll('[name=subject]:checked').length,2);
  document.querySelector('[data-view="majorCutoffs"]').click();assert.equal($('result-title').textContent,'专业实际录取分数');
  assert.equal($('round').value,'all','专业线入口不能默认隐藏高校汇总数据');
  input('query','玉林');input('batch','all');input('round','首轮');assert.ok(document.querySelectorAll('.result-card').length>0);assert.equal($('round-field').hidden,false);
  input('query','齐齐哈尔');input('round','录取汇总（含征集）');assert.ok(document.querySelectorAll('.result-card').length>0);assert.match($('results-list').textContent,/录取汇总（含征集）/);
  document.querySelector('[data-view="special"]').click();assert.equal($('special-view').hidden,false);assert.equal($('query-layout').hidden,true);
  input('special-query','哈尔滨工业大学');assert.match($('special-list').textContent,/100 分制/);assert.match($('special-list').textContent,/加权成绩入围线/);assert.ok(!$('special-list').textContent.includes('entrance-weighted'));
  input('special-query','厦门大学');assert.match($('special-list').textContent,/1000 分制/);
  input('special-query','华中科技大学');assert.ok([...document.querySelectorAll('#special-list .detail-plan strong')].some(e=>e.textContent==='化学：519 分'));assert.match($('special-list').textContent,/519\.097109105/);
  input('special-query','中央民族大学');assert.match($('special-list').textContent,/广西计划：本省不适用/);
  input('special-query','重庆大学');assert.match($('special-list').textContent,/本轮原页无法重读/);
  input('special-query','不存在的大学XYZ');assert.match($('special-list').textContent,/没有匹配/);
  document.querySelector('[data-view="sources"]').click();assert.equal($('sources-view').hidden,false);assert.match($('coverage-detail').textContent,/部分覆盖/);
  assert.ok(document.querySelectorAll('#sources-list a').length>=18);
  document.querySelector('[data-view="gaps"]').click();assert.equal($('gaps-view').hidden,false);assert.equal($('query-layout').hidden,true);
  assert.match($('gap-overview').textContent,/1,961/);
  input('gap-query','广西大学');assert.match($('gap-list').textContent,/专业组代码/);assert.equal(document.querySelectorAll('.gap-card').length,1);
  document.querySelector('[data-school-query][data-destination="plans"]').click();assert.equal($('query').value,'10593');assert.equal($('query-layout').hidden,false);assert.equal($('kind').value,'all');
  assert.ok(document.querySelectorAll('.result-card').length>0);document.querySelector('[data-detail]').click();assert.match($('detail-content').textContent,/本专业尚待核实或关联/);$('close-detail').click();
  document.querySelector('[data-view="gaps"]').click();input('gap-query','不存在的院校XYZ');assert.match($('gap-list').textContent,/没有匹配院校/);
  input('gap-query','重庆三峡医药');document.querySelector('[data-school-query][data-destination="majorCutoffs"]').click();
  assert.ok([...document.querySelectorAll('.score.empty')].some(e=>e.textContent==='原文待核'));
  $('unknown').checked=false;$('unknown').dispatchEvent(new window.Event('input',{bubbles:true}));assert.equal(document.querySelectorAll('.score.empty').length,0);
  assert.equal(document.querySelectorAll('a[href^="javascript:"]').length,0);
  dom.window.close();
});

test('文件加载失败显示可恢复提示，不把空数据当作成功', async()=>{
  const html=await readFile(new URL('../site/index.html',import.meta.url),'utf8');
  const dom=new JSDOM(html,{url:'https://example.test/'});
  globalThis.document=dom.window.document;globalThis.window=dom.window;globalThis.localStorage=dom.window.localStorage;
  globalThis.fetch=async()=>({ok:false,status:503});
  await import('../site/app.js?error-test');
  for(let i=0;i<100&&document.documentElement.dataset.ready===undefined;i++)await new Promise(resolve=>setTimeout(resolve,10));
  assert.equal(document.documentElement.dataset.ready,'error');
  assert.equal(document.getElementById('data-error').hidden,false);
  assert.match(document.getElementById('error-detail').textContent,/503/);
  dom.window.close();
});
